import React, { useState } from 'react';

// ─── Toggle Switch ─────────────────────────────────────────────────────────────
const Toggle = ({ checked, onChange, id }) => (
  <label className="relative inline-flex items-center cursor-pointer shrink-0" htmlFor={id}>
    <input id={id} checked={checked} onChange={onChange} className="sr-only peer" type="checkbox" />
    <div className="w-10 h-5 bg-slate-200 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:bg-[#0d9488]"></div>
  </label>
);

// ─── Toggle Row ────────────────────────────────────────────────────────────────
const ToggleRow = ({ icon, label, description, checked, onChange, id }) => (
  <div className="flex items-center justify-between p-3.5 rounded-xl bg-slate-50 border border-slate-200/70 gap-4">
    <div className="flex items-center gap-3 min-w-0">
      <div className="w-8 h-8 rounded-lg bg-white border border-slate-200/80 text-slate-500 flex items-center justify-center shrink-0 shadow-sm">
        <span className="material-symbols-outlined text-[18px]">{icon}</span>
      </div>
      <div className="min-w-0">
        <h5 className="text-xs font-semibold text-slate-800 leading-snug">{label}</h5>
        <p className="text-[11px] text-slate-400 mt-0.5 leading-snug">{description}</p>
      </div>
    </div>
    <Toggle checked={checked} onChange={onChange} id={id} />
  </div>
);

export default function Settings() {
  const [labName, setLabName] = useState('CellInsight Diagnostic Laboratory');
  const [address, setAddress] = useState('123 Shivajinagar, Pune, Maharashtra');
  const [city, setCity] = useState('Pune');
  const [state, setState] = useState('Maharashtra');
  const [pin, setPin] = useState('411005');
  const [phone, setPhone] = useState('+91 98765 43210');
  const [email, setEmail] = useState('lab@cellinsightlab.com');
  const [website, setWebsite] = useState('www.cellinsightlab.com');
  const [isEditingLab, setIsEditingLab] = useState(false);
  const [savedLab, setSavedLab] = useState(true);

  const [disclaimer, setDisclaimer] = useState(
    'This report is generated by CellInsight Lab as a research prototype for laboratory assistance. The system does not provide autonomous medical diagnosis. Final interpretation remains with qualified professionals.'
  );
  const [footer, setFooter] = useState(
    'Confidential Diagnostic Summary • Generated for certified laboratory hematology use only.'
  );

  const [toggles, setToggles] = useState({
    logo: true,
    contact: true,
    reviewer: true,
    regNum: true,
    signature: true,
  });

  const setToggle = (key) => setToggles(t => ({ ...t, [key]: !t[key] }));

  const handleSaveLab = () => { setSavedLab(true); setIsEditingLab(false); };

  return (
    <div className="flex flex-col w-full max-w-7xl mx-auto space-y-6 pb-10">
      {/* Page Header */}
      <div>
        <h1 className="text-[28px] font-semibold text-slate-900 tracking-tight leading-tight">Settings</h1>
        <p className="text-xs text-slate-500 mt-1">Manage your laboratory information and report configuration.</p>
      </div>

      {/* ── Laboratory Profile Card ─────────────────────────────────────────── */}
      <div className="bg-white rounded-xl border border-slate-200/80 shadow-sm p-6">
        {/* Card Header */}
        <div className="flex items-center justify-between pb-5 border-b border-slate-100 mb-6">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-teal-50 flex items-center justify-center text-teal-700 border border-teal-100 shrink-0">
              <span className="material-symbols-outlined text-[22px]">business</span>
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900">Laboratory Profile</h3>
              <p className="text-xs text-slate-500 font-normal mt-0.5">Official facility details displayed on diagnostic summaries and exported reports.</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <span className="px-3 py-1.5 bg-teal-50 text-teal-700 text-[11px] font-semibold rounded-lg border border-teal-100">
              Facility ID: LAB-IND-1002
            </span>
            {!isEditingLab ? (
              <button
                className="flex items-center gap-1.5 px-3 py-1.5 border border-slate-200 rounded-lg text-xs font-semibold text-slate-700 hover:bg-slate-50 transition-colors"
                onClick={() => setIsEditingLab(true)}
                type="button"
              >
                <span className="material-symbols-outlined text-[14px]">edit</span>Edit
              </button>
            ) : (
              <div className="flex gap-2">
                <button className="flex items-center gap-1.5 px-3 py-1.5 border border-slate-200 rounded-lg text-xs font-semibold text-slate-600 hover:bg-slate-50 transition-colors" onClick={() => setIsEditingLab(false)} type="button">Cancel</button>
                <button className="flex items-center gap-1.5 px-3 py-1.5 bg-[#0d9488] text-white rounded-lg text-xs font-semibold hover:bg-teal-700 transition-colors shadow-sm" onClick={handleSaveLab} type="button">
                  <span className="material-symbols-outlined text-[14px]">save</span>Save Changes
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Card Body */}
        <div className="grid grid-cols-12 gap-6 items-start">
          {/* Logo Section */}
          <div className="col-span-12 md:col-span-3 flex flex-col items-center justify-center border-r border-slate-100 pr-6">
            <div className="relative w-28 h-28 rounded-2xl bg-slate-50 border border-slate-200/80 shadow-sm flex items-center justify-center">
              <div className="w-16 h-16 rounded-full bg-teal-600 flex items-center justify-center text-white font-bold text-xl select-none">CI</div>
              <button className="absolute -bottom-2 -right-2 w-7 h-7 bg-[#0d9488] text-white rounded-full flex items-center justify-center shadow hover:bg-teal-700 transition-colors">
                <span className="material-symbols-outlined text-[14px]">edit</span>
              </button>
            </div>
            <span className="text-[11px] text-slate-400 mt-3 font-medium">Laboratory Logo</span>
          </div>

          {/* Middle Column */}
          <div className="col-span-12 md:col-span-5 space-y-4">
            {[
              { label: 'Laboratory / Clinic Name', val: labName, set: setLabName, key: 'labName' },
              { label: 'Address', val: address, set: setAddress, key: 'address' },
              { label: 'City', val: city, set: setCity, key: 'city' },
              { label: 'State / Province', val: state, set: setState, key: 'state' },
              { label: 'PIN / ZIP Code', val: pin, set: setPin, key: 'pin' },
            ].map(({ label, val, set, key }) => (
              <div key={key} className="flex items-start gap-3">
                <span className="w-44 text-[11px] text-slate-400 font-medium shrink-0 pt-0.5">{label}</span>
                {isEditingLab ? (
                  <input
                    className="flex-1 text-xs text-slate-800 font-semibold border border-slate-200 rounded-lg px-2.5 py-1.5 focus:outline-none focus:ring-1 focus:ring-teal-600 bg-slate-50"
                    value={val}
                    onChange={e => set(e.target.value)}
                  />
                ) : (
                  <span className="text-xs font-semibold text-slate-800">{val}</span>
                )}
              </div>
            ))}
          </div>

          {/* Right Column */}
          <div className="col-span-12 md:col-span-4 space-y-4 pl-4 border-l border-slate-100">
            {[
              { label: 'Phone Number', val: phone, set: setPhone, key: 'phone' },
              { label: 'Email', val: email, set: setEmail, key: 'email' },
              { label: 'Website', val: website, set: setWebsite, key: 'website' },
            ].map(({ label, val, set, key }) => (
              <div key={key} className="flex items-start gap-3">
                <span className="w-32 text-[11px] text-slate-400 font-medium shrink-0 pt-0.5">{label}</span>
                {isEditingLab ? (
                  <input
                    className="flex-1 text-xs text-slate-800 font-semibold border border-slate-200 rounded-lg px-2.5 py-1.5 focus:outline-none focus:ring-1 focus:ring-teal-600 bg-slate-50"
                    value={val}
                    onChange={e => set(e.target.value)}
                  />
                ) : (
                  <span className="text-xs font-semibold text-slate-800 truncate">{val}</span>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ── Report Settings Card ────────────────────────────────────────────── */}
      <div className="bg-white rounded-xl border border-slate-200/80 shadow-sm p-6">
        {/* Card Header */}
        <div className="flex items-center gap-3 pb-5 border-b border-slate-100 mb-6">
          <div className="w-10 h-10 rounded-lg bg-teal-50 flex items-center justify-center text-teal-700 border border-teal-100 shrink-0">
            <span className="material-symbols-outlined text-[22px]">description</span>
          </div>
          <div>
            <h3 className="text-sm font-bold text-slate-900">Report Settings</h3>
            <p className="text-xs text-slate-500 font-normal mt-0.5">Configure default header, footer, and clinical disclosures for AI blood smear analysis reports.</p>
          </div>
        </div>

        {/* Card Body */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-start">
          {/* Left: Toggle List */}
          <div>
            <h4 className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-3">Report Elements</h4>
            <div className="space-y-2.5">
              <ToggleRow id="t-logo"      icon="image"         label="Include Laboratory Logo in Header"     description="Display your laboratory logo at the top of every report"       checked={toggles.logo}      onChange={() => setToggle('logo')} />
              <ToggleRow id="t-contact"   icon="call"          label="Include Laboratory Contact Information" description="Show facility address, phone, email and website"               checked={toggles.contact}   onChange={() => setToggle('contact')} />
              <ToggleRow id="t-reviewer"  icon="person"        label="Include Reviewer Name & Designation"   description="Display signing pathologist details from your profile"         checked={toggles.reviewer}  onChange={() => setToggle('reviewer')} />
              <ToggleRow id="t-reg"       icon="verified_user" label="Include Medical Registration Number"   description="Show registration number for clinical validity"                checked={toggles.regNum}    onChange={() => setToggle('regNum')} />
              <ToggleRow id="t-sig"       icon="draw"          label="Include Digital Signature"             description="Apply saved digital signature to reports"                     checked={toggles.signature} onChange={() => setToggle('signature')} />
            </div>
          </div>

          {/* Right: Disclaimer & Footer */}
          <div>
            <h4 className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-3">Report Disclaimer & Footer</h4>
            <div className="space-y-5">
              {/* Disclaimer */}
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1.5">
                  Mandatory AI Clinical Disclaimer <span className="text-rose-500">*</span>
                </label>
                <textarea
                  className="w-full text-xs text-slate-700 bg-slate-50 border border-slate-200 rounded-xl p-3.5 focus:outline-none focus:ring-1 focus:ring-teal-600 focus:border-teal-600 resize-none font-normal leading-relaxed transition"
                  rows="4"
                  maxLength={200}
                  value={disclaimer}
                  onChange={e => setDisclaimer(e.target.value)}
                />
                <div className="text-right text-[11px] text-slate-400 mt-1 font-medium">{disclaimer.length}/200</div>
              </div>
              {/* Footer */}
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1.5">
                  Custom Footer Text <span className="text-slate-400 font-normal">(Optional)</span>
                </label>
                <textarea
                  className="w-full text-xs text-slate-700 bg-slate-50 border border-slate-200 rounded-xl p-3.5 focus:outline-none focus:ring-1 focus:ring-teal-600 focus:border-teal-600 resize-none font-normal leading-relaxed transition"
                  rows="3"
                  maxLength={200}
                  value={footer}
                  onChange={e => setFooter(e.target.value)}
                />
                <div className="text-right text-[11px] text-slate-400 mt-1 font-medium">{footer.length}/200</div>
              </div>
              {/* Save button */}
              <div className="flex justify-end">
                <button
                  className="flex items-center gap-1.5 px-4 py-2 bg-[#0d9488] text-white rounded-lg text-xs font-semibold hover:bg-teal-700 transition-colors shadow-sm"
                  type="button"
                >
                  <span className="material-symbols-outlined text-[14px]">save</span>Save Report Settings
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
